### PR TITLE
Mp3 playback

### PR DESCRIPTION
**Pull request by 9names**

### CODE REVIEW

**Comment by thejpster** [comment]
What kinds of MP3s (data rate, sample rate) will this play?

**Comment by 9names** [comment]
This example should play anything mpeg1 layer 3 correctly (32khz, 44.1khz, 48khz), stereo or mono, vbr or cbr.
Tested with 64kbit/sec and 160kbit/sec.
If you resize the audio slice depending on the return value of the decode function, it should also support mpeg2 later 3 (which supports more frequencies than I can name).
The high-level API doesn't skip id3 headers so I would recommend files that do not have them - I'm doing conversion to wave then re-encode to MP3 to ensure that is true in my testing.

The playback rate will only be correct for 
48khz stereo until there is a way to reconfigure audio codec ic playback format via a syscall

**Comment by 9names** [comment]
I take it back, it absolutely does not deal with VBR in its current state.

I've added support for finding and decoding the header portion of id3v2 tags to the library.
I brought the code for skipping the id3v2 header over from my hosted example but haven't tested it on neotron yet.
in theory, more mp3's should "just work" now.

**Comment by 9names** [comment]
i've updated the code to resize the output slice once we know how many output samples per frame.
tested with mpeg1 layer 3, mpeg2 layer 3 @22050hz, and mpeg 2.5 layer 3 @8000hz.
tested on neotron.

**Comment by thejpster** [comment]
So I love that this exists, but I am unlikely to merge it as-is. I do, however, suddenly feel motivated to give you a file open/close/read/write API so you can make it into an application! As a bonus, all your application code will always be in RAM.

**Comment by 9names** [comment]
Totally fine, I agree it would be better as a user application.
I did mostly use it as a real-world test of the lib, and for that use it was invaluable.
Sorry for noise, feel free to close this PR (or I will do so tomorrow)

**Comment by thejpster** [comment]
Don't apologise, it's great to see!

**Comment by 9names** [comment]
Closing, will implement this as a user application

**Pull request closed without merging**
